spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ddl-demo
    username: postgres
    password: root
  liquibase:
    change-log: classpath:liquibase/liquibase.properties